os: Visual Studio 2019

build: off

clone_folder: c:\gopath\src\github.com\assetcloud\chain

environment:
  GOPATH: c:\gopath

before_test:
  - set PATH=C:\go119\bin;%PATH%
  - set GOROOT=C:\go119

test_script:
  - go version
  - go env
  - go env -w CGO_ENABLED=0
  - go build -o build/chain.exe github.com/assetcloud/chain/cmd/chain
  - go build -o build/chain-cli.exe github.com/assetcloud/chain/cmd/cli
